tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "error-container": "#93000a",
                "surface-container": "#201f1f",
                "surface-container-low": "#1c1b1b",
                "on-tertiary-fixed-variant": "#474746",
                "on-surface-variant": "#c2c6d6",
                "on-secondary-fixed": "#1c1b1b",
                "on-tertiary-container": "#2a2a2a",
                "on-secondary-container": "#b7b5b4",
                "surface-container-high": "#2a2a2a",
                "primary-fixed": "#d8e2ff",
                "tertiary-fixed": "#e4e2e1",
                "on-tertiary-fixed": "#1b1c1c",
                "surface-dim": "#131313",
                "on-surface": "#e5e2e1",
                "surface-container-lowest": "#0e0e0e",
                "surface-tint": "#adc6ff",
                "tertiary-fixed-dim": "#c8c6c5",
                "secondary-fixed-dim": "#c8c6c5",
                "error": "#ffb4ab",
                "on-error-container": "#ffdad6",
                "inverse-on-surface": "#313030",
                "secondary-container": "#474746",
                "surface-bright": "#3a3939",
                "primary-container": "#4d8eff",
                "tertiary-container": "#929090",
                "background": "#131313",
                "inverse-surface": "#e5e2e1",
                "on-primary-container": "#00285d",
                "on-primary-fixed-variant": "#004395",
                "secondary": "#c8c6c5",
                "surface": "#131313",
                "inverse-primary": "#005ac2",
                "on-primary-fixed": "#001a42",
                "surface-container-highest": "#353534",
                "on-secondary-fixed-variant": "#474746",
                "on-secondary": "#313030",
                "primary": "#adc6ff",
                "tertiary": "#c8c6c5",
                "on-tertiary": "#303030",
                "on-background": "#e5e2e1",
                "secondary-fixed": "#e5e2e1",
                "outline-variant": "#424754",
                "surface-variant": "#353534",
                "on-primary": "#002e6a",
                "primary-fixed-dim": "#adc6ff",
                "outline": "#8c909f",
                "on-error": "#690005"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "margin-page": "48px",
                "section-gap": "80px",
                "stack-lg": "32px",
                "container-max-width": "1200px",
                "stack-md": "16px",
                "stack-sm": "8px",
                "gutter": "24px",
                "unit": "8px"
            },
            "fontFamily": {
                "technical-caps": ["Inter"],
                "label": ["Inter"],
                "h1": ["Inter"],
                "h3": ["Inter"],
                "h2": ["Inter"],
                "body-lg": ["Inter"],
                "body-md": ["Inter"]
            },
            "fontSize": {
                "technical-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
                "label": ["14px", {"lineHeight": "1", "letterSpacing": "0", "fontWeight": "500"}],
                "h1": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "h3": ["24px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600"}],
                "h2": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}]
            }
        },
    },
};
